apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mystockwebserviceapp-dep
  name: mystockwebserviceapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mystockwebserviceapp-dep
  template:
    metadata:
      labels:
        app: mystockwebserviceapp-dep
    spec:
      containers:
      - image: temitopeajisafe/mystockwebserviceapp
        name: mystockwebserviceapp
        env:
          - name: NDAYS
            valueFrom:
              configMapKeyRef:
                name: stockwebserviceapp-env
                key: NDAYS
          - name: SYMBOL
            valueFrom:
              configMapKeyRef:
                name: stockwebserviceapp-env
                key: SYMBOL
          - name: APIKEY
            valueFrom:
              secretKeyRef:
                name: webservice-apikey
                key: apikey
---
apiVersion: v1
kind: Service
metadata:
  name: mystockwebserviceapp-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: mystockwebserviceapp-dep
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
---
apiVersion: v1
data:
  NDAYS: "7"
  SYMBOL: MSFT
kind: ConfigMap
metadata:
  name: stockwebserviceapp-env
  namespace: default
  selfLink: /api/v1/namespaces/default/configmaps/stockwebserviceapp-env
---
apiVersion: v1
kind: Secret
metadata:
  name: webservice-apikey
data:
  apikey: QzIyN1dEOVczTFVWS1ZWOQ==
