name: Docker Image CI

on:
  pull_request:
    types:
    - closed
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Maven Action
      uses: s4u/setup-maven-action@1.7.0
      with:
        java-version: 19
        maven-version: 3.9.0

    - name: Build Stock app jar file
      run: mvn package

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag temitopeajisafe/mystockwebserviceapp:latest

    - name: Docker Push
      run: docker push temitopeajisafe/mystockwebserviceapp:latest
